###

GET http://localhost:8080/software-engineers

###

POST http://localhost:8080/software-engineers
Content-Type: application/json

{
  "name": "James",
  "techStack": "Js, node, react"
}

###
DELETE http://localhost:8080/software-engineers/1

###
PUT http://localhost:8080/software-engineers/1
Content-Type: application/json

{
  "name": "John Doe",
  "techStack": "Java, Spring Boot, PostgreSQL"
}

###
GET http://localhost:8080/tasks


###
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Finish Spring Boot project",
  "description": "Complete the beginner CRUD app",
  "status": "In Progress",
  "dueDate": "2025-08-15"
}



###
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Finish Spring Boot project",
  "description": "Complete the beginner CRUD app",
  "status": "Done",
  "dueDate": "2025-08-15"
}

###
DELETE http://localhost:8080/tasks/1


